- id: danger
  name: danger
  description: formalize your team etiquette
  language: node
  stages:
    - pre-commit
  entry: danger local
  args:
    - --base=main
    - --dangerfile=dangerfile.lite.ts
    - --staging
  pass_filenames: false
  always_run: true
